### ISSUE TITLE
About the TP parameter in the paper

### ISSUE THREAD

**Issue by dkjsednfkjsn** [tiev-tongji/LIMOT#4]
Dear author, thank you for your excellent work. I recently read your paper and you described the TP indicator as: "Here TP [%] stands for the ratio of the number of tracked frames to the number of the frames of the object's ground truth trajectory." I would like to ask why the TP indicator of most sequences is not high for 3D object tracking?

**Comment by Sonne-Zhu** [comment]
The IoU threshold for evaluating TP is taken as 0.25. This threshold is not very high and thus leads to frequent id switching during tracking, I removed the part where the id switches frequently and only evaluated trajectories where the tracing id is constant and continuous. Therefore the TP here is not meant to reflect the tracking performance, but just to show the relative tracking length of the object. In the previous version of this paper, here we directly use "Tracked frame length" instead of TP. I hope my answer solved your question.
